go-nv/goenv

README.md
Install from a private tap since the upstream formula was not accepted
=> Updated Homebrew installation instructions

plugins/go-build/README.md
This may not be totally correct - there are some references to CPython - but its slightly less confusing than the last version.
=> Cleanup pyenv references

.travis.yml
You'll need to enable travis, but this should start getting goenv in a place where we can make changes and actually verify that things work...
=> Add testing support

plugins/go-build/share/go-build/1.7.5
Because "install_freebsd_32bit" and "install_freebsd_64bit" is not working for Ubuntu 16.10, please change them to "install_bsd_32bit" and "install_bsd_64bit". These commands work for me well.
=> modified FreeBSD command

libexec/goenv-init
Try to add a start of answer to #21.
I am not a bash guy, so this may not be idiomatic.
=> Setup GOROOT on init.

plugins/go-build/share/go-build/1.8.1
I added the location of go 1.8.1 to go-build recipes :)
=> Add 1.8.1 to go-build recipes

libexec/goenv-init, libexec/goenv-sh-shell, test/init.bats, test/shell.bats
The `setenv` function in fish shell has changed in fish-shell/fish-shell@75600b6.
This function in `libexec/nodenv-init` produces `setenv: Too many arguments` error.
We should use `set` command with `-gx` option.
=> Prefer 'set' command to 'setenv' function for fish shell

libexec/goenv-exec, libexec/goenv-init
This PR will solve https://github.com/syndbg/goenv/issues/26
The followings are the points of this PR, but I'm not sure whether it's perfectly correct.
Point1: If `$(goenv version) == system`, don't set `GOROOT` in `libexec/goenv-exec`. Because `GOROOT` of system's go depends on how users installed go in system.
Point2: It's not necessary to set `GOROOT` in the script of `goenv init -`
- In case of system's go, goenv shouldn't touch `GOROOT` by the same reason in Point1.
- In other case(using goenv's go), `GOROOT` will be set in [here](https://github.com/syndbg/goenv/compare/master...kosukemori:remove-goroot?expand=1#diff-1b9493738f8dcd19f48cf92919daf168R39). So it's not necessary in `goenv init -`
=> Remove GOROOT when system's go

plugins/go-build/share/go-build/1.10rc2, plugins/go-build/share/go-build/1.8.7, plugins/go-build/share/go-build/1.9.4
[security] Go 1.8.7, Go 1.9.4, and Go 1.10rc2 are released
https://groups.google.com/forum/#!msg/golang-nuts/Gbhh1NxAjMU/dfW69X50AgAJ
=> 1.10rc2 1.8.7 1.9.4

plugins/go-build/share/go-build/1.10.2, plugins/go-build/share/go-build/1.9.6
See https://groups.google.com/forum/#!searchin/golang-announce/go$201.10.2%7Csort:date/golang-announce/qXEbop4t-Wg/tOHb-KE3BAAJ and https://golang.org/dl/#stable.
Is it possible to scrape https://golang.org/dl/#stable page to generate go version files automatically?
=> Add go 1.10.2 and 1.9.6 versions.

plugins/go-build/bin/go-build
In my machine `uname -m` returns `amd64` so I fixed logic for determining architecture in `plugins/go-build/bin/go-build` especially in BSD-related function. It may be suggested to add similar architecture determining code for other OS.
In addition I fixed trivial typo.
=> Adaptation for BSD on amd64 arch. & Fixed typo for BSD on 32 bit arch.

plugins/go-build/share/go-build/1.11beta2
Add go 1.11beta2 so that we can start downloading it and trying out `go mod`!
Links retrieved from https://golang.org/dl/
=> Add go 1.11beta2

plugins/go-build/share/go-build/1.10.4, plugins/go-build/share/go-build/1.11.0
🎉 🎉 🎉 
https://groups.google.com/forum/#!msg/golang-announce/O7POXMK3xbM/Ia8ObPyWDgAJ
=> add 1.11.0 and 1.10.4

plugins/go-build/share/go-build/1.10.6, plugins/go-build/share/go-build/1.11.3
Add Go versions `1.10.6` and `1.11.3`. The links where fetched from https://golang.org/dl/
These 2 versions were recently released as a security release ([link](https://groups.google.com/forum/#!msg/golang-announce/Kw31K8G7Fi0/z2olKn-QCAAJ)).
=> Add go 1.10.6 and 1.11.3

plugins/go-build/bin/go-build
`go-build` fails if curl or wget does not exist, but no error message is displayed.
I fixed it.
```
docker run --rm -it ubuntu bash
```
```
root@b0da95c4ca42:/# apt-get update 2>&1 > /dev/null && apt-get install -y git ca-certificates 2>&1 > /dev/null
debconf: delaying package configuration, since apt-utils is not installed
root@b0da95c4ca42:/# which curl; echo $?
1
root@b0da95c4ca42:/# which wget; echo $?
1
root@b0da95c4ca42:/# git clone https://github.com/syndbg/goenv.git ~/.goenv
Cloning into '/root/.goenv'...
remote: Enumerating objects: 29, done.
remote: Counting objects: 100% (29/29), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 13864 (delta 10), reused 21 (delta 5), pack-reused 13835
Receiving objects: 100% (13864/13864), 2.50 MiB | 2.06 MiB/s, done. …
```
=> `go-build` fails if curl or wget does not exist, but no error message is displayed.

INSTALL.md
Fix $PATH, add security warning, add whitespace between other notes for better readability. I expect this all to get reworked anyway for #98.
Closes #99.
=> move $GOPATH/bin to end of $PATH

INSTALL.md
This PR updates the documentation to include installation via ZPlug plugin.
The plugin at https://gitlab.com/RiverGlide/zsh-goenv.git is pretty straightforward.
It uses git submodules to checkout goenv, and the plugin file itself adds goenv and goenv-install to the path as well as calling eval $(goenv init -)
=> Add ZPlug installation instructions

plugins/go-build/bin/go-build, plugins/go-build/share/go-build/1.16beta1
It seems like that the official build now provides support for Apple Silicon since 1.16beta1.
https://golang.org/dl/#go1.16beta1
=> Support darwin-arm64 arch on 1.16beta1

plugins/go-build/bin/go-build, plugins/go-build/share/go-build/1.14.0, plugins/go-build/share/go-build/1.14.1, plugins/go-build/share/go-build/1.14.10, plugins/go-build/share/go-build/1.14.11, plugins/go-build/share/go-build/1.14.12, plugins/go-build/share/go-build/1.14.13, plugins/go-build/share/go-build/1.14.2, plugins/go-build/share/go-build/1.14.3, plugins/go-build/share/go-build/1.14.4, plugins/go-build/share/go-build/1.14.5, plugins/go-build/share/go-build/1.14.6, plugins/go-build/share/go-build/1.14.7, plugins/go-build/share/go-build/1.14.8, plugins/go-build/share/go-build/1.14.9, plugins/go-build/share/go-build/1.15.0, plugins/go-build/share/go-build/1.15.1, plugins/go-build/share/go-build/1.15.2, plugins/go-build/share/go-build/1.15.3, plugins/go-build/share/go-build/1.15.4, plugins/go-build/share/go-build/1.15.5, plugins/go-build/share/go-build/1.15.6, plugins/go-build/share/go-build/1.16beta1, plugins/go-build/test/fixtures/definitions/1.2.0, plugins/go-build/test/fixtures/definitions/1.2.2, plugins/go-build/test/goenv-install.bats
I added current supported go versions, 1.14, 1.15, and 1.16beta1. 
I tested this branch by MacBook Air (M1, 2020) and [Parallels Technical Preview](https://www.parallels.com/blogs/parallels-desktop-apple-silicon-mac/).
Travis CI test is [passed](https://travis-ci.org/github/blp1526/goenv/builds/753786570).
---
At [additional commit](https://github.com/blp1526/goenv/commit/072cb9c8bc07d5b77b8ed1fe8f3b1df9ff642e0f), I tried to add `arch: arm64` to .travis.yml, but [test failed by timeout for some reasons](https://travis-ci.org/github/blp1526/goenv/builds/753788187).
Although, test succeeded at local machine.
I'm sorry that I don't know how to fix this Travis CI test problem.
But I think this PR is useful for some users, so I make this PR without updating `.travis.yml`.
=> Add Linux arm 64bit

libexec/goenv-init, test/goenv-init.bats
- always export GOENV_ROOT
- do not append to PATH if entry already exists
=> clean up init function

.travis.yml, libexec/goenv-sh-rehash
When rehash is executed and GOENV_DISABLE_GOPATH is 0 (default)
the code should use currentVersionName instead becasue GOENV_VERSION is
not set.
=> ISSUE-169: GOENV_GOPATH_PREFIX does not work as expected

plugins/go-build/share/go-build/1.16.3, plugins/go-build/test/goenv-install.bats
Address #173 (Add go 1.16.3).
> go1.16.3 (released 2021/04/01) includes fixes to the compiler, linker, runtime, the go command, and the testing and time packages. See the Go 1.16.3 milestone on our issue tracker for details.
https://golang.org/doc/devel/release.html#go1.16
=> Add go1.16.3 (#173)

libexec/goenv-version-file-read
The use of POSIX regex makes goenv more portable -- namely, it allows goenv to
run on FreeBSD 13, where `regex(3)` is now strictly POSIX.
=> Use a POSIX-compatible regex in goenv-version-file-read

plugins/go-build/share/go-build/1.17rc1, plugins/go-build/test/goenv-install.bats
Go 1.17rc1 has also been released. Would you please support it? (Ref. #184)
=> Add 1.17rc1

plugins/go-build/bin/go-build
Address [Issue #172](https://github.com/syndbg/goenv/issues/172)
- `curl`
- Enable `--progress-bar` option.
- Disable `-s (--silent)` option suppressing progress-bar.
- `wget`
- Enable `--show-progress` option.
- Enable `-q (--quiet)` option to suppress result message such as:
`2021-07-26 02:04:05 URL:https://dl.google.com/go/go1.17rc1.darwin-amd64.tar.gz [135933957/135933957] -> "Go Darwin 64bit 1.17rc1.tar.gz" [1]`
- Both
- Indicators write characters one by one.
- Prompt needs to show them immediately without buffering by the redirect.
- `curl`
- Two indicators are shown. The first indicator is redirect response (code: 302).
```bash
$ goenv install 1.17rc1
Downloading go1.17rc1.darwin-amd64.tar.gz...
-> https://golang.org/dl/go1.17rc1.darwin-amd64.tar.gz …
```
=> Show progress bar during download tarball

test/test_assert_helpers.bash
which might not be installed, but type is a bash builtin.
=> test_assert_helper: use type -aP instead of which -a

src/configure, src/shobj-conf
This fixes building the extension on macOS 12.
=> Update realpath extension source with upstream changes

plugins/go-build/share/go-build/1.18rc1, plugins/go-build/test/goenv-install.bats
I followed https://github.com/syndbg/goenv/pull/212 as a template for this change and have successfully installed the darwin ARM version locally, however I am yet to run `make test` as I am on a mac. I am working on setting up a linux VM to run it but thought I would raise this PR now in case you are able to test and merge it before I manage to get it set up
=> Adds support for 1.18rc1 release

plugins/go-build/share/go-build/1.18.0
details: https://groups.google.com/g/golang-announce/c/6gJm7mgF6rw
Go 1.18 has been published so this pull request adds that version.
=> Support 1.18.0

plugins/go-build/bin/go-build
Sometimes we want to use x86_64 version on M1 Mac for some dependence issue.
Use an environment variable `FORCE_DARWIN_ARCH` to support this feature.
usage:
```bash
FORCE_DARWIN_ARCH=x86_64 goenv install 1.18.1
FORCE_DARWIN_ARCH=arm64 goenv install 1.18.1
```
=> feat: suport force darwin arch

plugins/go-build/share/go-build/1.18.3
Checksum Mismatch Fix (Resolves #230):
The .pkg checksum was referenced instead of the .tar.gz. All other checksums were verified and correct per the [Downloads Page](https://go.dev/dl#go1.18.3)
=> Go 1.18.3 Fix tar.gz MacOS checksum

plugins/go-build/share/go-build/1.19beta1, plugins/go-build/test/goenv-install.bats
Hi, Go 1.19beta1 just got out, adding it to goenv so it's easy for people to install it.
=> Add go1.19beta1 support

plugins/go-build/bin/go-build, plugins/go-build/test/goenv-install.bats
Missed a patch version in go build
=> install latest patch in go-build script

CHANGELOG.md, libexec/goenv---version, plugins/go-build/bin/go-build, plugins/go-build/test/goenv-install.bats, test/goenv--version.bats
Resolves `2.0.0beta11` being printed
=> fix version printout for `goenv --version`; update changelog

plugins/go-build/share/go-build/1.19.6, plugins/go-build/share/go-build/1.20.1
There were some pretty big CVEs so expect a lot of people to be upgrading to 1.19.6 and 1.20.1 soon.
See: https://go.dev/dl/#go1.20
=> Add support for go 1.19.6 and 1.20.1

plugins/go-build/share/go-build/1.19.9, plugins/go-build/share/go-build/1.20.4
https://github.com/syndbg/goenv/issues/298
=> Support go1.20.4 and go1.19.9 (#298)

INSTALL.md
Without this step, the following error occurs after following step 6 on Ubuntu
```
goenv: 'go' command not found
The 'go' command exists in these Go versions:
1.20.4
```
=> Add goenv global step

Makefile, README.md, libexec/goenv
Fix minor bug with GOENV_AUTO_INSTALL
Also add documentation to resolve #329 
Add Makefile step `test-target` to allow users to test specific files in BATS.
=> Fix: GOENV_AUTO_INSTALL

plugins/go-build/share/go-build/1.19.13
Most Go projects use outdated dependencies and unsupported Go versions like 1.19, at least offer them the last backported fixes.
=> chore: Add 1.19.13 definition to goenv

libexec/goenv, libexec/goenv-version-file-read, test/goenv-version-file-read.bats
go 1.21.x introduces the idea of toolchains.
Add support for switching goenv version based on go.mod file when toolchain version is present.
=> go.mod: add toolchain support

plugins/go-build/share/go-build/1.20.14
It seems the bot missed an important security release 😉
[go1.20.14 (released 2024-02-06)](https://go.dev/doc/devel/release#go1.20.14)
=> [goenv-bot]: Add 1.20.14 definition to goenv

.gitattributes
GitHub "Languages" statistics only consider file extensions, not contents.
Now they are not correct:
* Improve `Languages` statistics by reclassifying files without extension
=> chore: Display better code statistics

libexec/goenv-installed, plugins/go-build/bin/go-build
* Restore support for release candidates in `local`, `global`, `install` and `installed`
* `install 20rc1` installs 1.20rc2 (using latest release candidate like for minor versions)
* There are no tests yet
* `install 1.20rc1` installs the latest release candidate rc2, like it does for other minor versions (1.22 installs 1.22.6)
* goenv supports only a fraction of release candidates (it doesn't sync them like final releases)
* goenv does not allow installing an arbitrary version (unknown to goenv hashsums in `plugins/go-build/share/go-build`)
=> fix: Restore support for release candidates

plugins/go-build/bin/go-build
When sha256sum is run, I can see that it complains about the use of the --quiet flag, which does not have any effect when not verifying two checksums match.
$ goenv install 1.23.1
sha256sum: the --quiet option is meaningful only when 
verifying checksums
Try 'sha256sum --help' for more information.
Downloading go1.23.1.linux-arm64.tar.gz...
This can be shown outside goenv as well for both the sha256sum and sha1sum facilities on my device.
For example:
➜  ~ echo test | sha256sum --quiet
sha256sum: the --quiet option is meaningful only when 
verifying checksums
Try 'sha256sum --help' for more information.
➜  ~ echo $?
1
➜  ~ echo test | sha256sum 
f2ca1bb6c7e907d06dafe4687e579fce76b37e4e93b7605022da52e6ccc26fd2  -
➜  ~ echo $?
0
➜  ~ sha256sum --version
sha256sum (GNU coreutils) 9.5 …
=> Fix warning from sha256sum, sha1sum

plugins/go-build/bin/go-build
As reported in #403 version 2.2.7 has broken `goenv` on certain operating systems / environment e.g. AWS build images.
The PR #401 made `sha256sum` functional again but exposed a white-space comparison issue i.e. on systems using sha256sum would eventually lead to a failure in `verify_checksum` i.e.
```
+++++ sha256sum
++++ output='542d3c1705f1c6a1c5a80d5dc62e2e45171af291e755d591c5e6531ef63b454e  -'
++++ echo '542d3c1705f1c6a1c5a80d5dc62e2e45171af291e755d591c5e6531ef63b454e '
+++ echo '542d3c1705f1c6a1c5a80d5dc62e2e45171af291e755d591c5e6531ef63b454e '
++ local 'computed_checksum=542d3c1705f1c6a1c5a80d5dc62e2e45171af291e755d591c5e6531ef63b454e '
++ '[' -n '542d3c1705f1c6a1c5a80d5dc62e2e45171af291e755d591c5e6531ef63b454e ' ']'
++ '[' …
```
=> sanitize whitespace from checksums

.github/CODEOWNERS, libexec/goenv-init, libexec/goenv-installed, libexec/goenv-prefix, libexec/goenv-version-file-write, libexec/goenv-version-name, test/goenv-global.bats, test/goenv-init.bats, test/goenv-local.bats, test/goenv-version-file-write.bats, test/goenv.bats
Resolves:
#386 
#389 
Fixes POSIX compliance
Fixes go.mod support for major/minor/patch revisions
=> Fix Issues From Previous Merges

libexec/goenv-commands
We dont need to echo the versions in the loop. If you do this for every path entry in $PATH this can take forever.
=> Cache versions and make it faster

libexec/goenv-commands
Eliminate the need for iterating over the user's paths to search for `goenv-`
=> dont use the user's paths. Instead use compgen

libexec/goenv-init, test/goenv-init.bats
Just use the ${variable:-} syntax to accept unset variables
Our Yunohost helper is broken since the 2.2.10 because we source goenv-init with `set -u` and we don't define the optional environment variables.
=> goenv-init: Fix use of optional variables that should not crash the calling shell if unset

libexec/goenv-init
Cut time by 75%
~ via 🐹 v1.23.4 via 🐍 v3.12.8 (main) on ☁️
➜  time eval "$(goenv init -)"
real	0m0.755s
user	0m0.138s
sys		0m0.207s
~ via 🐹 v1.23.4 via 🐍 v3.12.8 (main) on ☁️
➜  time eval "$(goenv init - --no-rehash)"
real	0m0.407s
user	0m0.099s
sys		0m0.140s
After fix:
~ via 🐹 v1.23.4 via 🐍 v3.12.8 (main) on ☁️
➜  time eval "$(goenv init - --no-rehash)"
real	0m0.133s
user	0m0.032s
sys		0m0.051s
Signed-off-by: Justin Lecher <justin.lecher@astrazeneca.com>
=> fix: missing exclusion of rehash on init

libexec/goenv-version-file-read
Old go.mod behavior was Major.Minor. Now they support patch revisions as well
=> Add support for major.minor.patch go.mod and toolchain

README.md
No need to manually record PWD and to change back to previous directory if you let a subshell do it for you.
Fixes https://github.com/go-nv/goenv/issues/458
=> Make AWS Codebuild instructions simpler.

plugins/go-build/bin/goenv-install, plugins/go-build/test/goenv-install.bats, test/goenv.bats
Also remove the "<definition-file>" variant from the documentation as that does not seem to work.
Fixes https://github.com/go-nv/goenv/issues/457
=> Document "go install" without explicit version.

INSTALL.md
The installation instructions say to make the shell init script execute the output of `goenv init -`. That output contains this among other things:
```
export PATH="${GOENV_ROOT}/shims:${PATH}"
```
The main point of that line is to make the `go` command resolve to `$GOENV_ROOT/shims/go` such that `goenv` has control over the default `go`.
The installation instructions later say to add this after the eval in order to let "goenv manage GOPATH and GOROOT":
```
export PATH="$GOROOT/bin:$PATH"
export PATH="$PATH:$GOPATH/bin"
```
This effectively overrides the first line as `$GOROOT/bin` is also expected to contain a `go` binary. However that binary is not controlled by `goenv`. Furthermore AFAICT these two lines do not make "goenv manage GOPATH and GOROOT".
This has confused at least [one …
=> Don't suggest adding GOROOT/bin and GOPATH/bin to the PATH.

libexec/goenv-version-file-read, test/goenv-version-file-read.bats
Kudos to @CharlyReux and @RomainLefeuvre for spotting this and suggesting the fix.
=> fix(cve-2022-35861): backport pyenv fix
