- plugins/go-build/share/go-build/1.7.0
- plugins/go-build/share/go-build/1.7.1
- plugins/go-build/share/go-build/1.7.3
This provides go-build recipes from 1.7 to 1.7.3.
> Add go-build recipes for 1.7

- plugins/go-build/share/go-build/1.7.4
Thank you for developing awesome tool.
I added downloads list for go 1.7.4.
> add downloads list for 1.7.4

- plugins/go-build/share/go-build/1.9.0
> add 1.9.0 recipes

- plugins/go-build/share/go-build/1.6.4
> Adding go verison 1.6.4

- plugins/go-build/share/go-build/1.10beta2
url and sha referenced from https://golang.org/dl/
Thanks a lot!
> add 1.10beta2

- plugins/go-build/share/go-build/1.10rc1
URL and SHA referenced from https://golang.org/dl/
Thanks a lot!
> add 1.10rc1

- plugins/go-build/share/go-build/1.10.0
https://blog.golang.org/go1.10
> Add 1.10.0 release

- plugins/go-build/share/go-build/1.10.1
- plugins/go-build/share/go-build/1.9.5
Go 1.10.1 and Go 1.9.5 are released
https://groups.google.com/forum/#!topic/golang-announce/IkPkOF8JqLs
> Add 1.10.1 and 1.9.5

- plugins/go-build/share/go-build/1.10.3
- plugins/go-build/share/go-build/1.9.7
🎉 🎉 🎉 
https://groups.google.com/forum/#!topic/golang-announce/_S9YQriFKuU
> add 1.10.3 and 1.9.7

- plugins/go-build/share/go-build/1.11beta3
🎉
https://golang.org/dl/#unstable
> Add go 1.11beta3

- plugins/go-build/share/go-build/1.11rc2
Add Go 1.11rc2
https://groups.google.com/d/topic/golang-announce/zb6p0aFMBJM/discussion
https://golang.org/dl/#go1.11rc2
> Add Go 1.11rc2

- plugins/go-build/share/go-build/1.10.5
- plugins/go-build/share/go-build/1.11.2
🎉 🎉 🎉 
https://groups.google.com/forum/#!msg/golang-announce/XwnlNhVZE5o/P1n8QJprAwAJ
> add 1.11.2 and 1.10.5

- plugins/go-build/share/go-build/1.10.7
- plugins/go-build/share/go-build/1.11.4
https://groups.google.com/forum/#!msg/golang-announce/7LQy56br6Y4/wV4RaajpCAAJ
> Add 1.11.4 and 1.10.7

- plugins/go-build/share/go-build/1.12beta1
https://golang.org/dl/#go1.12beta1
> :tada: add 1.12beta1

- plugins/go-build/share/go-build/1.12beta2
- plugins/go-build/test/goenv-install.bats
https://golang.org/dl/#go1.12beta2
> :tada: add 1.12beta2

- plugins/go-build/share/go-build/1.12rc1
- plugins/go-build/test/goenv-install.bats
https://golang.org/dl/#go1.12rc1
> add 1.12rc1

- plugins/go-build/share/go-build/1.13beta1
- plugins/go-build/test/goenv-install.bats
https://golang.org/issue/new
https://golang.org/dl/#go1.13beta1
> add 1.13beta1

- plugins/go-build/share/go-build/1.13rc1
- plugins/go-build/test/goenv-install.bats
> :tada: add 1.13rc1

- plugins/go-build/share/go-build/1.13rc2
- plugins/go-build/test/goenv-install.bats
https://golang.org/dl/#go1.13rc2
https://tip.golang.org/doc/go1.13
> add 1.13rc2

- plugins/go-build/README.md
I saw typo while reading the documentation.
> Fixed typo

- plugins/go-build/share/go-build/1.14rc1
- plugins/go-build/test/goenv-install.bats
https://groups.google.com/forum/#!topic/golang-announce/mB1Mp9RlQw8
https://golang.org/dl/#go1.14rc1
> add 1.14rc1

- libexec/goenv-rehash
- libexec/goenv-whence
- libexec/goenv-which
https://github.com/syndbg/goenv/issues/30
Thanks for https://github.com/kadaan
https://github.com/syndbg/goenv/issues/30#issuecomment-560240354
https://github.com/kadaan/goenv-goget-rehash
> automatic shims

- plugins/go-build/share/go-build/1.15rc2
- plugins/go-build/test/goenv-install.bats
https://groups.google.com/g/golang-announce/c/G3atWQdoyvw/m/03XzzSXgAAAJ
https://golang.org/dl/#go1.15rc2
> add 1.15rc2

- libexec/goenv
- test/goenv.bats
> search relative to bin_path for plugins

- plugins/go-build/share/go-build/1.16beta1
- plugins/go-build/test/goenv-install.bats
https://groups.google.com/g/golang-announce/c/2-Rj3P5uRLs/m/mYxD2RJkAQAJ?pli=1
https://golang.org/dl/#go1.16beta1
> Add 1.16beta1

- ENVIRONMENT_VARIABLES.md
- libexec/goenv-exec
- libexec/goenv-sh-rehash
- test/goenv-sh-rehash.bats
I'm open to other implementations and wording, but I'd like to find a way to get something like this out soon. Let me know what you think. Thanks!
fixes #147
> add GOENV_APPEND_GOPATH and GOENV_PREPEND_GOPATH options

- plugins/go-build/share/go-build/1.18beta1
- plugins/go-build/test/goenv-install.bats
With generics, there's likely going to be quite a bit of interest towards this one.
> Add 1.18beta1

- plugins/go-build/share/go-build/1.18beta2
- plugins/go-build/test/goenv-install.bats
https://go.dev/blog/go1.18beta2
> Add 1.18beta2

- plugins/go-build/share/go-build/1.17.9
> Support go 1.17.9

- INSTALL.md
Fix https://github.com/syndbg/goenv/issues/234
> Remove redundant command prompts

- INSTALL.md
> Doc: simplify git cmd for upgrade & checkout version

- libexec/goenv-init
Fixes security vulnerability described in #247.
> move shims to end of $PATH

- plugins/go-build/bin/goenv-install
> move latest patch code below once definition path is set by goenv local

- libexec/goenv-version-name
- libexec/goenv-which
- test/goenv-version.bats
> Resolve init rehash issue

- plugins/go-build/share/go-build/1.18.9
- plugins/go-build/share/go-build/1.19.4
https://groups.google.com/g/golang-announce/c/L_3rmdT0BMU
> Support Golang 1.18.9 and 1.19.4

- plugins/go-build/share/go-build/1.18.10
- plugins/go-build/share/go-build/1.19.5
- plugins/go-build/share/go-build/1.20rc2
1.20rc2: https://groups.google.com/g/golang-announce/c/muM4ByrIMbM
1.19.5, 1.18.10: https://groups.google.com/g/golang-announce/c/wrmRT7JlevE
> Support 1.18.10, 1.19.5, 1.20rc2

- plugins/go-build/share/go-build/1.20.0
https://groups.google.com/g/golang-announce/c/QMK8IQALDvA
> Support 1.20

- CHANGELOG.md
- libexec/goenv---version
- plugins/go-build/bin/go-build
- plugins/go-build/test/goenv-install.bats
- test/goenv--version.bats
> chore: release 2.0.7

- plugins/go-build/share/go-build/1.19.10
- plugins/go-build/share/go-build/1.20.5
> Add Golang 1.19.10 and 1.20.5

- CHANGELOG.md
- COMMANDS.md
- ENVIRONMENT_VARIABLES.md
- Makefile
- libexec/goenv
- plugins/go-build/README.md
- plugins/go-build/bin/go-build
- plugins/go-build/bin/goenv-install
- plugins/go-build/test/goenv-install.bats
- plugins/go-build/test/goenv-uninstall.bats
- plugins/go-build/test/test_helper.bash
- scripts/latest_version.sh
- test/goenv-rehash.bats
- test/goenv-sh-rehash.bats
- test/goenv-version-file-read.bats
- test/goenv-which.bats
- test/goenv.bats
- test/test_helper.bash
Also update BATS to 1.10.0
Resolves #297 and #281
> Feature: Support silent install and GOENV_AUTO_INSTALL

- ENVIRONMENT_VARIABLES.md
- libexec/goenv-prefix
- libexec/goenv-version-name
- libexec/goenv-which
- plugins/go-build/bin/go-build
- plugins/go-build/test/installer.bats
- test/goenv-prefix.bats
- test/goenv-rehash.bats
- test/goenv-sh-rehash.bats
Resolve #296 
Resolve #363 
Resolve #358
> Fix Goenv Prefix, LS and Build Mirror behavior

- README.md
* Add latest release badge [![Latest Release](https://img.shields.io/github/v/release/go-nv/goenv.svg)](https://github.com/go-nv/goenv/releases/latest)
* Add License badge [![License](https://img.shields.io/badge/License-MIT-blue.svg)](https://github.com/go-nv/goenv/blob/main/LICENSE)
> feat: Add latest release and license badge

- README.md
* Add more badges (do they make sense?)
[![Go](https://img.shields.io/badge/Go-%2300ADD8.svg?&logo=go&logoColor=white)](https://go.dev/)
[![Bash](https://img.shields.io/badge/Bash-4EAA25?logo=gnubash&logoColor=fff)](https://github.com/go-nv/goenv)
[![Linux](https://img.shields.io/badge/Linux-FCC624?logo=linux&logoColor=black)](https://github.com/go-nv/goenv)
[![macOS](https://img.shields.io/badge/macOS-000000?logo=macos&logoColor=F0F0F0)](https://github.com/go-nv/goenv)
> feat: Add Go, Bash, Linux, macOS badges

- libexec/goenv-installed
- test/goenv-help.bats
- test/test_helper.bash
Attempt to resolve perf issues per #396
> Try and fix the perf issues with goenv installed
